# Generated by Django 4.2.20 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=155, verbose_name='Телефон')),
                ('e_mail', models.CharField(max_length=155, verbose_name='e_mail')),
                ('image', models.ImageField(upload_to='contacts/', verbose_name='Зображення')),
                ('details', models.TextField(max_length=450, verbose_name='Реквізити')),
                ('name', models.CharField(max_length=155, verbose_name='Контакти')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='ContactsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Геолокація')),
                ('name', models.CharField(max_length=155, verbose_name='Короткий опис')),
                ('map_url', models.URLField(verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Локацію',
                'verbose_name_plural': 'Локація',
            },
        ),
    ]
