# Generated by Django 4.2.20 on 2026-02-04 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
    ]
