# Редирект с HTTP на HTTPS
server {
    listen 80;
    server_name sich-energo.zp.ua www.sich-energo.zp.ua;
    return 301 https://$host$request_uri;
}

# Основной HTTPS-блок
server {
    listen 443 ssl;
    server_name sich-energo.zp.ua www.sich-energo.zp.ua;

    # Пути к сертификатам Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/sich-energo.zp.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sich-energo.zp.ua/privkey.pem;

    # Дополнительные SSL-настройки (рекомендуется)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 50M;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /robots.txt {
        alias /app/robots.txt;
    }

    location = /sitemap.xml {
        alias /app/sitemap.xml;
    }
}
