# Generated by Django 4.2.20 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('content_type', models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео')], max_length=10, verbose_name='Тип контенту')),
                ('content_file', models.FileField(upload_to='news/', verbose_name='Файл контента')),
                ('region', models.CharField(max_length=155, verbose_name='Регіон')),
                ('heading', models.CharField(max_length=155, verbose_name='Рубрика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Новину',
                'verbose_name_plural': 'Новини',
                'ordering': ['-created_at'],
            },
        ),
    ]
