# Generated by Django 4.2.20 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовок')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/service/', verbose_name='Відео')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Назва події')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Подію',
                'verbose_name_plural': 'Події',
            },
        ),
    ]
