# Generated by Django 4.2.20 on 2026-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва блоку')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('detail_url', models.URLField(blank=True, null=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блок',
            },
        ),
    ]
