# Generated by Django 4.2.20 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelitem',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блок (перелік продукції та послуг)'},
        ),
        migrations.AlterField(
            model_name='modelitem',
            name='image',
            field=models.ImageField(upload_to='main/', verbose_name='Зображення'),
        ),
    ]
