# Generated by Django 4.2.20 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsInform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Останні події')),
                ('image', models.ImageField(upload_to='company/', verbose_name='Зображення')),
                ('name', models.CharField(max_length=155, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Подію',
                'verbose_name_plural': 'Документи події',
            },
        ),
        migrations.CreateModel(
            name='DocumentsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Найменування')),
                ('image', models.ImageField(upload_to='company/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Презентація')),
                ('image', models.ImageField(default='deps/img/trans.png', upload_to='presentations/', verbose_name='Зображення')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('file_present', models.FileField(upload_to='presentations/files/', verbose_name='Файл для скачування')),
            ],
            options={
                'verbose_name': 'Презентацію',
                'verbose_name_plural': 'Презентація',
            },
        ),
        migrations.CreateModel(
            name='ReviewsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Додатковий сервіс')),
                ('image', models.ImageField(upload_to='company/', verbose_name='Зображення')),
                ('name', models.CharField(max_length=155, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Сервіс',
                'verbose_name_plural': 'Відгуки Сервіс',
            },
        ),
        migrations.CreateModel(
            name='ReviewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Назва компанії')),
                ('image', models.ImageField(upload_to='company/', verbose_name='Зображення')),
                ('description', models.TextField(verbose_name='Опис')),
                ('name', models.CharField(max_length=155, verbose_name='Трансформатор')),
                ('region', models.CharField(max_length=155, verbose_name='Регіон')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-id'],
            },
        ),
    ]
