# Generated by Django 4.2.20 on 2026-01-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsinfo',
            options={'verbose_name': 'Сервіс', 'verbose_name_plural': 'Відгуки Блок Додатковий Сервіс'},
        ),
    ]
