# Generated by Django 4.2.20 on 2026-01-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_reviewsinfo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentsInform',
        ),
    ]
