# Generated by Django 4.2.20 on 2026-02-04 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_delete_documentsinform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file_present',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Файл для скачування'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=cloudinary.models.CloudinaryField(default='deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='reviewsinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='reviewsitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
    ]
