# Generated by Django 4.2.20 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformKTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='КТП (опитовий лист)')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Відео')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('file_ol', models.FileField(upload_to='ktp/ol/', verbose_name='Файл для скачування')),
            ],
            options={
                'verbose_name': 'Опитувальний лист',
                'verbose_name_plural': 'КТП - Опитувальні листи',
            },
        ),
        migrations.CreateModel(
            name='InformTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Трансформатор (опитовий лист)')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Відео')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('file_ol', models.FileField(upload_to='transform/ol/', verbose_name='Файл для скачування')),
            ],
            options={
                'verbose_name': 'Опитувальний лист',
                'verbose_name_plural': 'Трансформатор - Опитувальні листи',
            },
        ),
        migrations.CreateModel(
            name='TransformItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Серія')),
                ('image', models.ImageField(upload_to='transform/item/', verbose_name='Зображення')),
                ('detail_url', models.URLField(blank=True, null=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Серію',
                'verbose_name_plural': 'Серія трансформатора',
            },
        ),
        migrations.CreateModel(
            name='TransformTm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Потужність трансформаторів ТМ та ТМЖ')),
                ('image', models.ImageField(upload_to='transform/tm/', verbose_name='Зображення')),
                ('file_tm', models.FileField(upload_to='transform/file/tm/', verbose_name='Скачати креслення трансформаторів ТМ та ТМЖ')),
            ],
            options={
                'verbose_name': 'Трансформатор ТМ та ТМЖ',
                'verbose_name_plural': 'Трансформатори ТМ та ТМЖ',
            },
        ),
        migrations.CreateModel(
            name='TransformTmg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Потужність трансформаторів ТМГ та ТМЖ')),
                ('image', models.ImageField(upload_to='transform/tmg/', verbose_name='Зображення')),
                ('file_tmg', models.FileField(upload_to='transform/file/tmg/', verbose_name='Скачати креслення трансформаторів ТМГ та ТМЖ')),
            ],
            options={
                'verbose_name': 'Трансформатор ТМГ та ТМЖ',
                'verbose_name_plural': 'Трансформатори ТМГ та ТМЖ',
            },
        ),
        migrations.CreateModel(
            name='TransformTmz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Трансформатори ТМЗ')),
                ('image', models.ImageField(upload_to='transform/tmz/', verbose_name='Зображення')),
                ('file_tmz', models.FileField(upload_to='transform/file/tmz/', verbose_name='Скачати креслення трансформаторів ТМЗ')),
            ],
            options={
                'verbose_name': 'Трансформатор ТМЗ',
                'verbose_name_plural': 'Трансформатори ТМЗ',
            },
        ),
        migrations.CreateModel(
            name='TransformYZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Трансформатори серії Y/Z')),
                ('image', models.ImageField(upload_to='transform/yz/', verbose_name='Зображення')),
                ('file_yz', models.FileField(upload_to='transform/file/yz/', verbose_name='Скачати креслення трансформаторів Y/Z')),
            ],
            options={
                'verbose_name': 'Трансформатор Y/Z',
                'verbose_name_plural': 'Трансформатори Y/Z',
            },
        ),
    ]
