# Generated by Django 4.2.20 on 2026-02-04 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informktp',
            name='file_ol',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Файл для скачування'),
        ),
        migrations.AlterField(
            model_name='informktp',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Відео'),
        ),
        migrations.AlterField(
            model_name='informtransform',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Відео'),
        ),
        migrations.AlterField(
            model_name='transformitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='transformtm',
            name='file_tm',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Скачати креслення трансформаторів ТМ та ТМЖ'),
        ),
        migrations.AlterField(
            model_name='transformtm',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='transformtmg',
            name='file_tmg',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Скачати креслення трансформаторів ТМГ та ТМЖ'),
        ),
        migrations.AlterField(
            model_name='transformtmg',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='transformtmz',
            name='file_tmz',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Скачати креслення трансформаторів ТМЗ'),
        ),
        migrations.AlterField(
            model_name='transformtmz',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='transformyz',
            name='file_yz',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Скачати креслення трансформаторів Y/Z'),
        ),
        migrations.AlterField(
            model_name='transformyz',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
    ]
