# Generated by Django 4.2.20 on 2026-02-08 18:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_informktp_file_ol_alter_informktp_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informtransform',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='', verbose_name='Відео'),
        ),
    ]
