# Generated by Django 4.2.20 on 2026-02-08 19:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_informtransform_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informtransform',
            name='file_ol',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Файл для скачування'),
        ),
        migrations.AlterField(
            model_name='informtransform',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Відео'),
        ),
    ]
